name: CI [cmake]

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            preset: windows-vs-msvc-x64
          - os: ubuntu-latest
            preset: linux-ninja-clang-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install -y mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - run: cmake --preset ${{ matrix.preset }}
      - run: cmake --build --preset ${{ matrix.preset }}-release
